Размечает главную страницу
htmlacademy-adaptive/2071173-cat-energy-26 pull request #2
Opened 2022-07-28 19:25 UTC by kokosmosss

2022-07-28 22:25 UTC, wrgraff requested changes
Хорошая работа! Я вижу, что где-то запуталась может немного, но основной подход поняла верно.

А, и еще. Я тут плейлист когда-то делал с [разметкой формы по БЭМу](https://youtube.com/playlist?list=PL6xpnt2woRKk0btmfzM2oR6-ste7wZUWm). Можешь глянуть в качестве доп инфы, там особенно про переиспользуемость много, она понадобится дальше =)

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +            </a>
`nav-list__link--current` это у нас модификатор. Модификатор это такая штука, чтобы с его помощью поменять свойство блока или элемента. То есть, для этого он и применяться должен к блоку или элементу, и он не может быть дан отдельному тегу.

Кстати, не очень понятно зачем тут `<span>` нужен вообще =)

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +    <div class="main-footer__copyright copyright">
У тебя вроде как блок `page-footer` же, а не `main-footer` =)
Чтобы находить такие чисто технические ошибки, поможет [этот инструмент от Йоксель](https://yoksel.github.io/html-tree/). Он умеет проверять правильность БЭМ-структуры документа.

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +    </a>
Мне не очень понятна логика разметки по БЭМу здесь.
Мы миксуем элемент хэдера с блоком логотипа. Выделяя логотип в отдельный БЭМ-блок, мы как бы определяем его независимость и самостоятельность. Но дальше у тебя внутри логотипа идет 2 тега: один элемент хэдера, а другой — элемент лого. Так как есть элемент чужого блока, независимость теряется. Ну и в целом это как-то странно:
- `.page-header__logo` `.logo`
  - `.page-header__logo-image`
  - `.logo__text`

Если объявляешь блок на каком-то уровне, то лучше чтобы элементы от родителя в него уже не просачивались. Тогда будет так:
- `.page-header__logo` `.logo`
  - `.logo__image`
  - `.logo__text`

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +      <b class="logo__text">Cat</b> Energy
Текст логотипа обязательно тоже вставлять картинкой. Текст может по разному рендериться или шрифт может не загрузиться: для логотипа это критично (если брендбук этого намеренно не допускает, но обычно там такого нет).
Поэтому, мы делаем логотипы картинками.

Ты можешь разделить тут лого на 2 картинки, а не одну, но только не текстом.

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +      <img class="page-header__logo-image page-header__logo-image--common" src="img/logo-primary.svg" width="34"
На данном этапе пока сложно понять насколько удачно модификатор подобран.
Может, после правок найдется вариант получше. Или можно пока от него избавиться.
Впрочем, можно и позже поправить, смотри как удобнее )

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +      <div class="page-nav__wrapper">
А ты уже точно просчитала как будешь верстать этот блок и уверена на 100%, что эта обертка нужна?

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +    <!-- я не стала выделять это в отдельный блок, т.к. это относится ко всей странице -->
Это конечно ничего не нарушает формально, но раз ты сама эту тему подняла... =)
БЭМ — это не про смысл, а про визуальное построение интерфейса. Если ты чувствуешь, что удобно создать отдельный блок — создай, даже если он выделит какой-то текст, не имеющий смысла без контекста.

За смысл у нас отвечает семантика. Например, чтобы не выделять этот блок логически, можно использовать `<div>`, а не `<section>`.

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +    <!-- логика: общий класс-блок для кнопки, класс-элемент для видоизменения кнопки, класс-элемент для расположения кнопки. правильно ли так рассуждать? -->
Логика звучит отлично!

Но есть косяк по синтаксису БЭМа: на блоке не может быть элемента этого же блока, потому что элементы обязательно должны быть внутри.
То есть, "класс-элемент для видоизменения кнопки" должен быть тогда "класс-модификатор для видоизменения кнопки"

Ну и я бы поставил не `button--for-program`, а `button--program`.
Но это уже так, мелочи: я предпочитаю покорче классы, а то БЭМ и так громоздкий. А кто-то любит более описательные =)

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +            <svg class="pack__button-icon"></svg>
А зачем ты заранее ставишь декоративную графику в разметку? Нам в принципе желательно декора в разметке избегать. А тут мы за оформление и не беремся еще.

Несколько таких элементов у тебя:
https://github.com/htmlacademy-adaptive/2071173-cat-energy-26/blob/c165e089a333d25d2435d56aed3928b25c338baa/source/index.html#L59
https://github.com/htmlacademy-adaptive/2071173-cat-energy-26/blob/c165e089a333d25d2435d56aed3928b25c338baa/source/index.html#L71
https://github.com/htmlacademy-adaptive/2071173-cat-energy-26/blob/c165e089a333d25d2435d56aed3928b25c338baa/source/index.html#L156
https://github.com/htmlacademy-adaptive/2071173-cat-energy-26/blob/c165e089a333d25d2435d56aed3928b25c338baa/source/index.html#L162
https://github.com/htmlacademy-adaptive/2071173-cat-energy-26/blob/c165e089a333d25d2435d56aed3928b25c338baa/source/index.html#L168
https://github.com/htmlacademy-adaptive/2071173-cat-energy-26/blob/c165e089a333d25d2435d56aed3928b25c338baa/source/index.html#L176

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +            <!-- вот тут я так понимаю нужен еще один класс, т.к. действие по клику будет разное, но может ли быть feachure__button-slim ? -->
Действие по клику одно: переход по ссылке.
Ссылки — разные, за них отвечает `href`.

Кажется, класс не нужен никакой

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +            <!-- аналогично. вот тут я так понимаю нужен еще один класс, т.к. действие по клику будет разное, но может ли быть feachure__button-pro ? -->
Не нужен по описанным выше причинам =)

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +          <span class="feachures__icon feachures__icon--leaf"><span class="visually-hidden">Иконка листок</span></span>
Все иконки тут в разметке. А они нам тут не нужны, потому что это декоративный элемент.
Тут еще и `visually-hidden` с текстом: но дает ли он полезную информацию для незрячего пользователя? Он все равно поймет смысл, только прослушав текст. А иконка ему наоборот не нужна.

Но есть и кое-что правильное: картинки мы и правда будем ставить через модификаторы. Но только он нужен для пункта списка.

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +          <span class="feachures__icon feachures__icon--time"><span class="visually-hidden">Иконка часы</span></span>
Кстати, всегда рекомендую при наличии вложенного тега давать новую строку.
Не то чтобы это важно, но считывается легче =)
```suggestion
          <span class="feachures__icon feachures__icon--time">
            <span class="visually-hidden">Иконка часы</span>
          </span>
```

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +        <dd class="example__param-description"> <small>Снижение веса</small></dd>
Теги `<small>` тут излишни, мы все равно будем задавать размер через стили

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +      </dl>
`dt` это description term, то есть термин.
`dd` это description definition, то есть описание или значение.

60 дней — это значение. То есть, все должно быть наоборот.
При этом обрати внимание: `dt` все равно должен быть впереди. Визуально их местами поменять мы сможем через стили.

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +      <dl class="example__param">
Это у тебя 2 списка выходит.
`dl` это такой список, где идут пары "ключ: значение" (или несколько значений, но это не важно сейчас).
Поэтому, у тебя выходит 2 списка, в каждом по одной паре. А должен быть один с двумя парами, раз уж на то пошло

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +      <!-- не уверена, что эта картинка контентная, т.к. она видоизменяется непонятным образом -->
Вполне контентная, она же показывает как меняется кот. Это важная информация, которую никак иначе не передать.

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +        alt="Изменения кота после смены питания.">
Предполагаю, что картинка "толстый кот", это не изменение после смены питания, а фото до похудения )
Будет еще фото "после".

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +            <span class="visually-hidden">Изменить кота на картинке.</span>
Изменить? )
Хочется попонятнее...

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +          <span class="example__range-after">Стало</span>
Есть подозрение, что это кнопки. Посмотри в стайлгайд: у них же есть состояния?

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +    <!-- валидатор ругается, говорит в aside нельзя adress вкладывать, хотя из спецификации я это не усмотрела. можно ли так? -->
Боюсь, дело в английском языке )
Пишется `address`. Да, это странное слово! Я так его и запомнил: не надо гадать где удвоение, оно везде! ))
Ну и тег само собой с ошибкой не существует. Странно, что валидатор именно акцент на недопустимость вложенности в `<aside>` говорит, но он вообще странненький.

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +      <b class="logo__text">Cat</b> Energy
Тут тоже картинку сделай

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +            <svg></svg>
Что иконка лишняя в разметке я уже писал, но смотри в целом логика странноватая:
мы ставим иконку по идее или модификатором со скрытым текстом или прям картинкой с альтом (или текстом, если это инлайн-свг как здесь)

А у тебя оба варианта наклевываются. Более правильный тут будет модификатор, так как иконка не смысловая, а смысл дает текст

2022-07-28 22:25 UTC, wrgraff commented on source/index.html
> +      </a>
Тоже, небольшой совет по коду.
Я вот сейчас почти упустил, что внутри ссылки есть и текст, и иконка, потому что когда открывающий и закрывающий тег на отдельных строках, как-то не смотришь есть ли после открывающего тега что-то еще, а смотришь только между тегами.

Поэтому, если уж тег разбит по строкам, то и внутри я бы рекомендовал писать так:
```suggestion
      <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive">
        HTML Academy
        <svg></svg>
      </a>
```

Это конечно не правило никакое и как писать в твоем проекте решать тебе. Но мне кажется, что так код поудобнее читается, поэтому просто советую присмотреться =)

2022-07-29 10:51 UTC, kokosmosss commented on source/index.html
> +            </a>
А как тогда быть если нам для реализации оформления нужна обертка? И по сути модификатор должен на нее и подвешиваться. Я в Седоне делала такое через span, т.к. другая реализация не придумалась. Тут аналогичная ситуация. Класс перевесила, мб будет какое-то иное решение, без span...

2022-07-29 11:01 UTC, kokosmosss commented on source/index.html
> +      <img class="page-header__logo-image page-header__logo-image--common" src="img/logo-primary.svg" width="34"
Пока оставлю, чтобы не забыть, что он меняется в зависимости от версии. В задании было написано не использовать -phone для мобильной версии. Хотя на мой взгляд тут как раз таки по версиям исключительно лого меняется и иной смысловой нагрузки там нет.

2022-07-29 11:04 UTC, kokosmosss commented on source/index.html
> +          <span class="example__range-after">Стало</span>
И правда, они. Поправила.

2022-07-29 11:09 UTC, kokosmosss commented on source/index.html
> +      <div class="page-nav__wrapper">
Тут показалось очевидным, т.к. всем ребятам с навигации придется прижаться вправо на планшете и декстопе))

2022-07-29 11:19 UTC, kokosmosss commented on source/index.html
> +    <!-- я не стала выделять это в отдельный блок, т.к. это относится ко всей странице -->
Да, тут наверное стоит использовать тогда div. Сделала.

2022-07-29 11:21 UTC, kokosmosss commented on source/index.html
> +    <!-- логика: общий класс-блок для кнопки, класс-элемент для видоизменения кнопки, класс-элемент для расположения кнопки. правильно ли так рассуждать? -->
Ага, вот это было не очевидно, поменяла.

2022-07-29 11:23 UTC, kokosmosss commented on source/index.html
> +            <svg class="pack__button-icon"></svg>
Я тут отталкивалась от изменения состояния - мы же тогда в разметку вставляем svg. Но сейчас еще раз посмотрела, там прозрачность просто добавляется, значит вроде можно и через css добавлять. Убираю.

2022-07-29 15:35 UTC, wrgraff commented on source/index.html
> +            </a>
Если нужна обёртка, то она тоже участвует в БЭМ. На какой элемент модификатор вешать — вопрос другой, ведь можно и через родителя стилизовать.
Но он точно не может быть отдельно сам по себе.

Ну и я всё-таки не понимаю зачем тут спан нужен будет для оформления. Думаю, и без него справимся 💪

2022-07-29 15:38 UTC, wrgraff commented on source/index.html
> +      <img class="page-header__logo-image page-header__logo-image--common" src="img/logo-primary.svg" width="34"
Но тебе не понадобятся модификаторы, потому что мы не будем менять логотип между версиями с их помощью.

На этом курсе ты научишься работать с тем, как менять картинки в зависимости от разрешения и плотности экрана через саму разметку

2022-07-29 15:42 UTC, wrgraff commented on source/index.html
> +      <div class="page-nav__wrapper">
Но можно прижать их внутри самого тега списка. Или вам список спозиционировать так, чтобы он был справа и по ширине контента.

На самом деле, тут и правда может понадобиться обёртка, но скорее для реализации разной сетки при адаптиве. Но вот будет ли она именно здесь — это вопрос )

2022-07-31 12:07 UTC, wrgraff requested changes
Очень хорошая работа, многие решения меня прям порадовали. Хорошо выделила блоки в списке каталога и на странице формы. Грамотно миксуешь блоки с элементами.
Держи звездочку: ⭐

2022-07-31 12:07 UTC, wrgraff commented on source/index.html
> +      <img class="logo__text" src="img/logo-text-small.svg" width="101" height="18" alt="Cat Energy.">
Преимущество svg как раз в том, что тебе не нужно иметь для одинаковой картинки разного размера несколько версий файлов.
Ты можешь поставить хоть 1010 на 180 пикселей — и логотип все равно будет четкий, потому что векторная графика хорошо масштабируется.

Разные картинки нужны будут для левой части с изображением. Но не из-за масштабирования, а потому что там больше деталей становится на крупных версиях

2022-07-31 12:07 UTC, wrgraff commented on source/index.html
> +    <div class="page-preamble">
Я обычно использую название `promo`. Еще популярный вариант — `hero`

2022-07-31 12:07 UTC, wrgraff commented on source/index.html
> +      <p class="page-main__intro page-preamble__intro">Занялся собой? Займись котом!</p>
Непонятно пока зачем тебе понадобился микс двух блоков. Ты хочешь как-то распределить логику между блоками?
Мне кажется, что пока что это скорее нам усложнит работу. Но посмотрим.

2022-07-31 12:07 UTC, wrgraff commented on source/index.html
> +        <button class="example__range-before">Было</button>
Кнопки появились, а атрибут `type` забыла =)

Кнопкам обязательно нужно прописать атрибут `type`.

По умолчанию кнопки работают как отправка формы. И если случайно из-за глюка в коде с незакрытым тегом формы наша кнопка отправит данные вместо переключения слайдера, то будет не здорово 🙃

Поэтому, таким кнопкам обязательно надо прописать `type="button"`.

Есть и еще момент. Надо прописывать и `type="submit"` тоже. Зачем прописывать значение по умолчанию?

А все просто: ради декларативности. То есть, если я посмотрю на кнопку, я *точно* буду знать какого она типа, если в ней этот тип написан. А если не написан, то буду сидеть и сомневаться: "это я забыл прописать или значение по умолчанию хотел использовать?".

2022-07-31 12:07 UTC, wrgraff commented on source/catalog.html
> +        <li class="catalog__item card card--show-more">
Я бы не сказал, что этот элемент по своему виду напоминает карточку товаров. Поэтому не рекомендую использовать для него тот же БЭМ-блок `card`.
Придется описывать слишком много других стилей и переназначать их.

2022-07-31 12:07 UTC, wrgraff commented on source/catalog.html
> +        <li class="catalog__item card card--show-more">
И так же стоит подумать, делать ли нам эти карточки частью одного единого списка. Ведь что такое список? Это коллекция однородных элементов, где каждый элемент имеет нечто общее со всеми.
Здесь у нас список товаров, каждый элемент значит — товар. А этот не товар.

Придется идти на компромисс скорее всего. Или оставить как сейчас — не совсем правильный список, с одним элементом-исключением, либо отказаться от списка и сделать набор элементов вроде `<article>`.

_P.S.: Есть конечно еще вариант с `display: contents`, но его поддержка пока слабовата и доступность как-то странно работает в некоторых случаях._

2022-07-31 12:07 UTC, wrgraff commented on source/catalog.html
> +          </div>
Маловато семантики. Можно хотя бы сделать параграфом общую орбертку, а не безликим дивом.

---

Есть еще вариант реально заморочиться и как и для карточек товаров сделать полноценный список определений, только здесь у нас будут скрыты термины:

```html
<dl class="card-row__list">
  <dt class="visually-hidden">Объем</dt>
  <dd class="card-row__definition">1 упаковка (30 г)</dd>

  <dt class="visually-hidden">Цена</dt>
  <dd class="card-row__definition">300 р.</dd>
</dl>
```

Не смотри, что классы другие — это из моего проекта пример.
Это уже будет задача со звездочкой =)

2022-07-31 12:07 UTC, wrgraff commented on source/form.html
> +            <a class="nav-list__link nav-list__link--current" href="index.html">
Активная ссылка не там )

2022-07-31 12:07 UTC, wrgraff commented on source/form.html
> +    <form class="page-main__form program-form" method="post" attion="https://echo.htmlacademy.ru/">
Очепятка
```suggestion
    <form class="page-main__form program-form" method="post" aсtion="https://echo.htmlacademy.ru/">
```

2022-07-31 12:07 UTC, wrgraff commented on source/form.html
> +        <div class="form-group__area field">
Если дивы для лейбла с полем делать параграфом, то они будут вообще без стилей смотреться чуть эстетичнее.
Но это прям если с ума сходить, то можно заморачиваться так. У тебя тут просто все очень хорошо, поэтому другого ничего и не посоветовать

2022-07-31 12:07 UTC, wrgraff commented on source/form.html
> +        </div>
У радио-кнопок им должно быть одинаковое, чтобы можно было выбрать одну опцию из нескольких.

Кстати, у чекбоксов одной группы тоже можно ставить одинаковые имена, то только обязательно указывать и их `value`. Тогда они будут приходить в данных формы как набор выбранных значений для этого общего имени.
А если сделать отдельные имена, то придут имена со значениями отмечено/не отмечено

2022-07-31 12:07 UTC, wrgraff commented on source/form.html
> +      <!-- я вот тут на "комментарии" ниже оставила form-group__legend, потому что он стилизован также. Йоксель говорит нельзя. Чувствую, у меня все же есть недопонимание со структурой БЭМ. Если она
Ну как раз по БЭМу это довольно неплохой ход. Единственное, что тут смущает — это название элемента.
То есть, в разметке так принято, что тег (именно тег) legend озаглавливает группу полей. А здесь не группа полей. И чисто из-за совпадения нейминга классов с именами тегов возникает диссонанс.

Ты можешь избавиться от этой проблемы довольно легко. И назвать заголовок группы, например `form-group__title`. Заголовок? Заголовок. Противоречия какие-то вызывает? Нет. Подходит в любом контексте для любого тега, главное – на вид чтобы был заголовочный.

2022-07-31 12:07 UTC, wrgraff commented on source/form.html
> +          rows="" cols=""></textarea>
Не оставляй пустые аттрибуты. Лучше удали, понадобятся — добавишь (скорее всего понадобится только `rows`)

2022-07-31 12:07 UTC, wrgraff commented on source/form.html
> +        </div>
Если используешь разные имена для чекбоксов, то `value` можно и опустить.

2022-07-31 12:07 UTC, wrgraff commented on source/form.html
> +        <button class="button button--order program-form__button" type="submit"> </button>
А где в кнопке текст? )))

2022-07-31 12:07 UTC, wrgraff commented on source/form.html
> +        <p class="program-form__disclaimer">* — Обязательные поля</p>
Вообще, кнопка и параграф вряд ли относятся к филдсету.
Скорее они должны идти после него.

2022-07-31 19:13 UTC, kokosmosss commented on source/index.html
> +      <p class="page-main__intro page-preamble__intro">Занялся собой? Займись котом!</p>
Если честно, я сама уже не пойму и не помню))) Возможно я рассуждала, что это и элементы main-страницы в целом и вступительного блока...

2022-07-31 19:18 UTC, kokosmosss commented on source/catalog.html
> +        <li class="catalog__item card card--show-more">
А мне она показалась на карточку похожа. Размер заголовка, размер и цвет нижнего параграфа и кнопка такая же по размеру... Но у него другая микросетка будет, наверное поэтому стоит другой блок сделать? Модификатором же такое нельзя поменять

2022-07-31 19:34 UTC, kokosmosss commented on source/catalog.html
> +          </div>
Интересно! Но я решила, что пусть будет меньше текста + разнообразие)) оставлю с параграфом.

2022-07-31 19:50 UTC, kokosmosss commented on source/form.html
> +      <!-- я вот тут на "комментарии" ниже оставила form-group__legend, потому что он стилизован также. Йоксель говорит нельзя. Чувствую, у меня все же есть недопонимание со структурой БЭМ. Если она
![image](https://user-images.githubusercontent.com/103606827/182042707-bf8ca191-b4e4-44f0-bce0-9f1272a184db.png)
Наименование поменяла. Попробую вставить картинку того, о чем я говорила. Вот этот момент смущает.

2022-07-31 19:59 UTC, kokosmosss commented on source/index.html
> +      <div class="page-nav__wrapper">
Убрала, потом по факту буду смотреть.

2022-07-31 20:07 UTC, kokosmosss commented on source/catalog.html
> +        <li class="catalog__item card card--show-more">
Мне кажется, что тут лучше оставить список. Пусть и не очень под карточку по смыслу подходит. Если делать через <article>, то придется добавлять доп. обертки, чтобы скомпоновать все в отдельную карточку. Я же верно понимаю, что в таком случае мне следует оставить catalog__item на этой li-шке? Ведь сама карточка как элемент раздела выглядит также. А за внутреннюю структуру у меня отдельный блок будет отвечать, это я поменяю.

2022-08-01 15:45 UTC, wrgraff commented on source/index.html
> +      <p class="page-main__intro page-preamble__intro">Занялся собой? Займись котом!</p>
Не забывай, что за семантику отвечают теги, а классы — за оформление.
Это как бы 2 слоя абстракции интерфейса, которые сосуществуют, но каждый сам по себе

2022-08-01 15:47 UTC, wrgraff commented on source/catalog.html
> +        <li class="catalog__item card card--show-more">
Модификатором можно поменять, но кажется, что модификатор по возможности лучше применять для более точечных вещей.
Конечно будут и исключения обязательно, но если есть возможность избежать такого, то лучше избежать

2022-08-01 15:48 UTC, wrgraff commented on source/catalog.html
> +        <li class="catalog__item card card--show-more">
Размеры текстов похожи, но по правде говоря можно много где на сайте найти схожие размеры текстов

2022-08-01 15:50 UTC, wrgraff commented on source/catalog.html
> +        <li class="catalog__item card card--show-more">
Про `catalog__item` совершенно верно.
Не очень только понял, почему `<article>` вызовет дополнительные обертки. По сути, количество элементов останется таким же.

Ну и я бы не сказал, что карточка как элемент раздела выглядит так же. Весь список — товары, а это — кнопка дозагрузки товаров. Смысл совсем другой.

Но дело твое =)

2022-08-01 15:56 UTC, wrgraff commented on source/form.html
> +        <p class="form-checks__area cheacks">
`cheacks` — странное слово, да еще и глагол...
Радио-баттоны у тебя так и названы `radio`. Можно и тут в лоб называть `checkbox`, например.

Есть еще хорошее слово `control` для элементов такого типа. Оно подойдет, если например ты верстаешь и радио-баттоны и чекбоксы одним блоком с разными модификаторами.

2022-08-01 15:56 UTC, wrgraff commented on source/form.html
> +      <!-- я вот тут на "комментарии" ниже оставила form-group__legend, потому что он стилизован также. Йоксель говорит нельзя. Чувствую, у меня все же есть недопонимание со структурой БЭМ. Если она
Так, ну тут мы вроде разобрались )

2022-08-01 15:57 UTC, wrgraff approved these changes
👍

2022-08-01 15:57 UTC, merged

2022-08-03 15:12 UTC, kokosmosss commented on source/index.html
> +      <p class="page-main__intro page-preamble__intro">Занялся собой? Займись котом!</p>
Прояснилось теперь. Они одинаковые на трех страницах))