Базовая стилизация страниц
htmlacademy-adaptive/2071173-cat-energy-26 pull request #3
Opened 2022-08-03 15:22 UTC by kokosmosss

2022-08-03 16:01 UTC, kokosmosss commented
у меня не вышло:
- подключить шрифт medium (500) к оформлению навигации, не поняла в чем ошибка.
- на станице каталога/формы перед логотипом - маленькая черточка от ссылки. пробовала удалять пробелы - не помогло. почему она возникает?

2022-08-04 19:26 UTC, wrgraff requested changes

2022-08-04 19:26 UTC, wrgraff commented on source/index.html
> +<body class="page__body page-container">
Я догадываюсь зачем на главной странице присутствует отдельный класс, но если бы смотрел не зная проекта, то мне было бы непонятно, почему некий "контейнер страницы" есть на главной, но нет на внутренних.
Название слишком абстрактное, кажется что это что-то общее, нужное везде. А оно наверное только для специфической задачи с добавлением зеленого половинчатого фона и кота.

2022-08-04 19:26 UTC, wrgraff commented on source/sass/variables-and-patterns.scss
> +// пока не применяю его, для наглядности
А зачем делать файл и для переменных и для утилитарных классов?
Мы можем сделать 2 разных файла прямо по назначению

2022-08-04 19:26 UTC, wrgraff commented on source/sass/style.scss
> +@import "variables-and-patterns.scss";
Переменные я бы вообще подключал в самом верху, так как они никакой код не создают, но зато могут понадобиться даже в файле шрифтов

2022-08-04 19:26 UTC, wrgraff commented on source/sass/style.scss
> +@import "button.scss";
По критерию [Б13](https://up.htmlacademy.ru/adaptive/26/criteries#b13) БЭМ-блоки должны быть в папке `blocks`, а не в корне

2022-08-04 19:26 UTC, wrgraff commented on source/sass/style.scss
> +// футер
Основная идея БЭМа в том, что любой блок может бить использован в любом месте. Поэтому, такая структуризация в общем-то уже на уровне методологии теряет свой основной смысл.
Вот у тебя же есть блок `.logo` — он и в хэдере и в футере. Куда его определить?
Ну и по тому же Б13 могут придраться.

Что касается удобства поиска файлов... Я пытался когда-то делать такую структуру и через пару лет возвращаясь к проекту очень сложно вспомнить куда я определил какой-то файл. И приходится по папкам искать.
Самое занятное, что когда они все в куче и по именам блоков — ты просто находишь его по алфавиту )

2022-08-04 19:26 UTC, wrgraff commented on source/sass/page.scss
> +  background-color: #ffffff;
Для единообразия можно и черный с белым положить в переменные.
Кстати, для документа это и так значения по умолчанию

2022-08-04 19:26 UTC, wrgraff commented on source/sass/index/packs.scss
> +}
Кажется, этот стиль — от блока `pack`, а не `packs`

2022-08-04 19:26 UTC, wrgraff commented on source/sass/button.scss
> +  outline: none;
Так, а как пользователи с клавиатуры будут фокусироваться на кнопках?
Я конечно понимаю, что возможно ты хочешь написать свои стили фокусировки, но пока их нет, не стоит и аутлайны сбрасывать.

2022-08-04 19:26 UTC, wrgraff commented on source/sass/button.scss
> +  box-sizing: border-box;
Крайне рекомендую сделать одно поведение для всего проекта. Я [подробно описал в заметке](https://frontend-design.notion.site/box-sizing-74c2b981a9624d03ba122967a529b9ad) почему именно такой подход рекомендую.

2022-08-04 19:26 UTC, wrgraff commented on source/sass/catalog/card-adds.scss
> +.catalog-adds__title {
Это файл для БЭМ-блока `.card-adds`, а это элемент другого блока

2022-08-04 19:26 UTC, wrgraff commented on source/sass/catalog/catalog-adds.scss
> +  background-image: url("../../img/present-block.png");
Неправильный путь к файлу. Препроцессор не умеет при сборке переписывать пути к картинкам. Это обычная статическая строка. Поэтому нам нужно писать путь исходя из того, где находится наш скомпилированный css-файл.

У нас директория `img` находится обычно рядом с директорией `css`, а значит нужно один раз выйти из директории(`../`) и зайти в картинки.

> Почему же при всем при этом картинки работают?
Потому, что лишние выходы на уровень выше не срабатывают, так как мы сразу попадаем в корневую директорию. Однако, если мы сделаем тоже самое на сервере с другими настройками, то будет проблема. Например, попробуй опубликовать свой пул-реквест в интерфейсе проверки задания (прямо в интерфейсе Академии есть такая кнопка)

2022-08-04 19:26 UTC, wrgraff commented on source/sass/catalog/catalog.scss
> +// стили для .catalog__list
Их же нет )))
Можно пока не создавать файлы для того, что не нужно еще

2022-08-04 19:26 UTC, wrgraff commented on source/sass/fonts.scss
> +  src: url("/sourse/fonts/oswaldregular.woff2") format("woff2");
Нууууу, касательно твоего вопроса...
1. У тебя не только один шрифт не работает, а все =)
  Чтобы посмотреть, какие шрифты реально рендерятся на странице, надо перейти во вкладку `Computed` и там внизу будет блок `Rendered fonts`. У меня почему-то все поехало в девтулзах Хрома, но по скрину можно понять где это посмотреть:
  ![изображение](https://user-images.githubusercontent.com/37917037/182934887-da55781e-2248-4efe-9ffe-9c091dab0bb7.png)
2. Пишется `source`
3. `source` — это корневая папка, из которой запускается сервер. Браузер ее не видит и не может туда войти. Поэтому, путь неверен. И вообще, стоит использовать относительные пути как и для картинок.

2022-08-04 19:26 UTC, wrgraff commented on source/sass/header/nav-list.scss
> +  outline: none;
Аутлайны как и на кнопках убираем только вместе с альтернативным решением.
Заранее уберешь — забудешь поставить и сайт потеряет в доступности.

2022-08-04 19:26 UTC, wrgraff commented on source/sass/index/example.scss
> +.example__range-after {
Сразу же закрадывается вопрос:
А нужно ли их делать разными элементами?

Возможно, больше подойдет модификатор. Или вообще ничего.

2022-08-04 19:26 UTC, wrgraff commented on source/sass/page.scss
> +  font-family: "Oswald", "Arial", sans-serif;
На сайте есть шрифты и семейства Oswald и Arial.
Во-первых, тебе на этом этапе по идее уже надо назначить где какой.
Во-вторых, стоит подумать: а какой шрифт больше подойдет как базовый? Обычно для базового берут то начертание, которым сделаны обычные параграфы текста. Это более спокойное и менее вычурное начертание. Так, если где-то вылезет недооформленный элемент, в нем будет не броский шрифт, а спокойный.

2022-08-04 19:29 UTC, wrgraff commented
> подключить шрифт medium (500) к оформлению навигации, не поняла в чем ошибка.

По этому вопросу там ответ есть в самом ревью. Со шрифтами еще придется повозиться.

> на станице каталога/формы перед логотипом - маленькая черточка от ссылки. пробовала удалять пробелы - не помогло. почему она возникает?

Это обычное подчеркивание у ссылок. Прямо как у текстовых (хотя, картинки и так отображаются как текст). За него отвечает `text-decoration`

2022-08-05 10:00 UTC, kokosmosss commented on source/index.html
> +<body class="page__body page-container">
Убрала, добавлю по факту стилизации.

2022-08-05 10:28 UTC, kokosmosss commented on source/sass/page.scss
> +  background-color: #ffffff;
Переменные добавила
А цвета не стоит все равно явно прописать?

2022-08-05 10:46 UTC, kokosmosss commented on source/sass/fonts.scss
> +  src: url("/sourse/fonts/oswaldregular.woff2") format("woff2");
А как понять какую папку браузер видит, а какую - нет?)

2022-08-05 11:31 UTC, kokosmosss commented on source/sass/button.scss
> +  box-sizing: border-box;
Поняла, думала кстати глобальный селектор запрещен, но на втором курсе видимо нет) не нашла в критериях

2022-08-05 19:29 UTC, wrgraff commented on source/catalog.html
> +        </a>
Эммм, а зачем поделила логотип на 2 ссылки, да еще и на 2 разных БЭМ-блока?
Логотип — это одна ссылка должна быть.

2022-08-05 19:29 UTC, wrgraff commented on source/catalog.html
> +    <header class="page-header page__header">
Сразу определись с порядком написания классов когда миксуешь блок и элемент.
Либо сперва классы элементов, либо сперва классы блоков. Сейчас вижу, что в коде встречается разный порядок, а это привносит некоторый бардак

2022-08-05 19:29 UTC, wrgraff commented on source/sass/patterns.scss
Может, лучше назвать файл `global` или `utils`?

2022-08-05 19:29 UTC, wrgraff commented on source/sass/variables.scss
> +$desktop-width: 1440px;
Лично я бы предпочел именование в стиле small / medium / large
Потому что у нас на самом деле нет гарантий, что на планшете не откроется desktop-версия размера или что-то в этом роде. Мы ведь на самом деле только размерами экранов оперируем, а не проверяем тип устройства (айпады про бывают размером как ноутбуки)

Ну и кстати такие именования легко расширяются, если нужно добавить размеров: xlarge, xsmall, xxlarge и так далее.

2022-08-05 19:29 UTC, wrgraff commented on source/sass/page.scss
> +  background-color: #ffffff;
Ну можно и прописать, если сильно хочется )

2022-08-05 19:29 UTC, wrgraff commented on source/sass/button.scss
> +  box-sizing: border-box;
Запрещен критерием [Д16](https://up.htmlacademy.ru/adaptive/26/criteries#d16), но `*` для `box-sizing` в списке исключений

2022-08-05 19:29 UTC, wrgraff commented on source/sass/fonts.scss
> +  src: url("/sourse/fonts/oswaldregular.woff2") format("woff2");
У нас сервер настроен из папки `source`, то есть она для него — корневая и в нее будет доступ как раз если поставить адрес от корня через `/`.
Сама настройка того, что именно эта папка является корневой — в файле `gulpfile`. Но мы до него дойдем когда будем изучать сборку (и даже перенастроим немного сервер)

2022-08-05 19:36 UTC, wrgraff requested changes
Все-таки, если забегаешь вперед — лучше делать это забегание в ветке следующего задания, иначе с добавлением кода по новому заданию будут добавляться ошибки и я не смогу принять ПР, и он у нас превратится в одно бесконечное ревью =)

2022-08-05 19:36 UTC, wrgraff commented on source/sass/blocks/page.scss
> +  margin: 0 auto;
Тут так не пойдет, это не Седона. У нас как минимум должны фоны секций тянуться до краев, а значит мы не можем центрировать весь документ одним махом.

2022-08-05 19:36 UTC, wrgraff commented on source/sass/blocks/page.scss
> +  min-width: 280px;
У нас уже есть минимальная ширина в 320 на самом теле документа. Зачем же нам ставить минимум на хэдер?

2022-08-05 19:36 UTC, wrgraff commented on source/sass/blocks/page.scss
> +  min-height: 264px;
А зачем минимальная высота? Высота должна создаваться контентом и отступами

2022-08-05 19:36 UTC, wrgraff commented on source/sass/blocks/page.scss
> +  flex-direction: column;
Я не фанат создания колонки для того, чтобы поставить элементы друг под другом, так как они и с обычным блочным отображением и так стоят друг под другом.
Лучше быть ленивее и ничего не делать пока не придется

2022-08-06 12:20 UTC, wrgraff approved these changes
Вот ты шустрая все-таки

2022-08-06 12:21 UTC, merged