Module4 task1
htmlacademy-adaptive/2071173-cat-energy-26 pull request #4
Opened 2022-08-08 21:13 UTC by kokosmosss

2022-08-08 21:27 UTC, kokosmosss commented
я честно говоря не поняла, надо ли было конкретно в этой домашке озадачиться расположением картинок в промоблоке. но я пока сделала схематично. если это сюда - доделаю.

2022-08-09 19:49 UTC, wrgraff requested changes
Обязательно еще нужно сделать центрирование

2022-08-09 19:49 UTC, wrgraff commented on source/catalog.html
> +  <main class="page-main page-main__section">
Но это же не элемент блока `page-main`, это он сам. Нельзя повесить элемент на собственный блок

2022-08-09 19:49 UTC, wrgraff commented on source/catalog.html
> +  <a class="page-footer__logo logo">
Зачем удалила ссылку? Она тут должна быть

2022-08-09 19:49 UTC, wrgraff commented on source/catalog.html
> +        <a class="social__link social__link--vkontakte" href="https://vk.com/htmlacademy"> vk
А что за буковки? Просто чтобы видно было?
Ну такое, можно же и забыть про них

2022-08-09 19:49 UTC, wrgraff commented on source/form.html
> +        <fieldset class="program-form__group program-form__grid2col program-form__grid4col form-checkbox">
Непонятно, `program-form__grid2col` и `program-form__grid4col` по сути друг другу противоречат

2022-08-09 19:49 UTC, wrgraff commented on source/form.html
> +    <a class="page-footer__logo logo">
Тут тоже видимо при копировании ссылка потерялась

2022-08-09 19:49 UTC, wrgraff commented on source/index.html
> +    <div class="page-promo page-promo--background">
Хм, а у нас есть какой-то другой блок `page-promo` на сайте? Зачем ему такой модификатор?

2022-08-09 19:49 UTC, wrgraff commented on source/sass/blocks/program-form.scss
> +}
У этих классов есть проблема: они ведут себя не очевидно при изменении размеров экрана. 2col работает со среднего размера, 4col — с большого. Как это понять, как помнить? Что мы будем делать, когда нам понадобится 4 колонки на мобильном?

Если уж ты хочешь пойти настолько абстрактным путем, то надо и эти нюансы продумывать. И придется использовать размеры в именованиях классов. Типа `.grid__columns--medium_4`, `.grid__columns--large_2`. И назначать их в стиле mobile first, чтобы medium работал от среднего и выше.
Пока я бы рекомендовал идти более "в лоб", чтобы не запутаться. Да и макет не располагает к универсальным решениям...

2022-08-09 19:49 UTC, wrgraff commented on source/sass/blocks/program-form.scss
> +    column-gap: 61px;
Обычно когда в макете встречаются числа типа "61" или "81" — это проблема макета.
Стоит такие расстояния округлять. А если есть возможность, то и вовсе округлять до числа, кратного 8 (но это другая история)

2022-08-09 19:49 UTC, wrgraff commented on source/sass/blocks/page-promo.scss
> +  background-size: 100%;
Картинка должна оставаться в центре, а не масштабироваться. А то жуть какая-то выходит:
![изображение](https://user-images.githubusercontent.com/37917037/183741741-e4ef4f83-7694-43ed-b38d-7f0da9ab0910.png)

2022-08-09 19:49 UTC, wrgraff commented on source/sass/blocks/page-promo.scss
> +      hsl(97 53% 47% / 85%)),
Зачем использовать градиент от края в край между совершенно одинаковыми цветами?

2022-08-09 19:49 UTC, wrgraff commented on source/sass/blocks/page-promo.scss
> +  position: absolute;
Зачем же на мобильнике делать абсолют, тут бы и так все легко заработало

2022-08-09 19:49 UTC, wrgraff commented on source/sass/blocks/page-main.scss
> +}
У нас же вроде бы в другом месте кот реализован?

2022-08-09 19:49 UTC, wrgraff commented on source/sass/blocks/page-footer.scss
> +    justify-content: space-between;
Раскидать так элементы конечно легко, но только они не попадут в макет, потому что ты создаешь равные расстояния между элементами. А они не равны, лого академии занимает больше места и сдвинет соцсети относительно центра левее.

2022-08-09 19:49 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    width: 45%;
Ну там совсем не 45%, а вполне определенная фиксированная ширина

2022-08-09 19:50 UTC, wrgraff commented
> я честно говоря не поняла, надо ли было конкретно в этой домашке озадачиться расположением картинок в промоблоке. но я пока сделала схематично. если это сюда - доделаю.

Это скорее к декоративным элементам работа, можно пока оставить как есть и там уже реализовать в деталях

2022-08-10 11:48 UTC, kokosmosss commented on source/sass/blocks/contacts.scss
> +    width: 45%;
А разве она не должна тянутся, когда ширина будет больше 1440px?

2022-08-10 11:49 UTC, kokosmosss commented on source/sass/blocks/page-footer.scss
> +    justify-content: space-between;
я вот сейчас набросала, как подумала можно это сделать. или так тоже не получится?)

2022-08-10 11:49 UTC, kokosmosss commented on source/sass/blocks/page-main.scss
> +}
Это осталось от прошлого варианта реализации, когда кот был сделан сразу с зеленым фоном.

2022-08-10 14:51 UTC, kokosmosss commented on source/catalog.html
> +        <a class="social__link social__link--vkontakte" href="https://vk.com/htmlacademy"> vk
Да, без них совсем неудобно. Подгружу иконки на след раз.

2022-08-10 15:55 UTC, kokosmosss commented on source/form.html
> +        <fieldset class="program-form__group program-form__grid2col program-form__grid4col form-checkbox">
Да вроде нет противоречия... какие-то блоки должны на планшете и десктопе встать в 2 колонки, а вот он конкретно: планшет - 2, десктоп - 4. Я попробовала переделать сейчас "в лоб", но у меня вышла вообще каша какая-то, т.к. блоки имеют одинаковые классы, надо создавать отдельные блоки (по типам данных) или использовать сложные селекторы. Какой-то простой способ это сделать я не нашла :( Поэтому я лучше пойду по пути с отдельными классами. По моему как раз наглядно будет из разметки, что происходит с компонентом.

2022-08-10 15:55 UTC, kokosmosss commented on source/index.html
> +    <div class="page-promo page-promo--background">
По поводу модификатора- делала отдельный, чтобы в дальнейшем можно было перевесить на другой элемент + может не быть фона вообще.

2022-08-10 16:06 UTC, kokosmosss commented on source/catalog.html
> +  <main class="page-main page-main__section">
я все время сталкиваюсь с этой проблемой и не понимаю, что тут делать?
модификатор для таких случаев же не подходит? делать обертку? я сделала. но так оберток слишком много может быть и кажется, что БЭМ только мешает...

2022-08-10 18:13 UTC, kokosmosss commented
я немного по разному сделала отступы на разных страницах (в верхних частях - заголовок и описание), т.к. я думаю, что все эти пути корректные и чтобы может быть ты посоветовал, если какой-то из путей более верный)) смотрела на элементы с рамками для наглядности.

2022-08-11 22:17 UTC, wrgraff commented on source/catalog.html
> +  <main class="page-main page-main__section">
Ну как что делать... Единообразие поддерживать.
Если у тебя на других страницах есть секшены, их которых состоит страница внутри мейна — надо придерживаться. Даже если она вроде бы на одной странице конкретной и не нужна, потому что она там одна: все равно она нужна. Потому что мы придерживаемся методологии, единообразия.

2022-08-11 22:21 UTC, wrgraff commented on source/form.html
> +        <fieldset class="program-form__group program-form__grid2col-medium program-form__grid4col-large  form-checkbox">
Жесть какая, тебя не пугают эти классы? )

2022-08-11 22:21 UTC, wrgraff commented on source/catalog.html
> +        <a class="social__link social__link--vkontakte" href="https://vk.com/htmlacademy"> vk
Можно размеры назначить и фон покрасить, чтобы видно было ссылки квадратные такие

2022-08-11 22:26 UTC, wrgraff commented on source/form.html
> +        <fieldset class="program-form__group program-form__grid2col program-form__grid4col form-checkbox">
Ну как нет... Я смотрю, тут 2 класса: 2 колонки и 4 колонки. Так 2 или 4?
Вообще, сложно это комментировать текстом, я бы это лучше обсудил в формате диалога, на консультации. У меня и примеры есть интересные на эту тему. Посмотрим как тот же Бутстрап работает и какие-то свои решения на примере моих проектов.

2022-08-11 22:30 UTC, wrgraff commented on source/index.html
> +    <div class="page-promo page-promo--background">
Типа, промо-блок, но без фона?
Слишком сложно, преждевременная оптимизация бывает вредна, тут надо осторожнее

2022-08-11 22:43 UTC, wrgraff commented on source/sass/blocks/page-promo.scss
> +    linear-gradient(to top, $white 24%, hsl(97 53% 47% / 85%) 24%),
А почему проценты... У тебя получается при изменении высоты и фон будет двигаться...

2022-08-11 22:43 UTC, wrgraff commented on source/sass/blocks/page-promo.scss
> +//  ну вот такое вот... но не получается теперь картинку по центру, вылезает зеленка сверху
А где `background-position` то чтобы располагать

2022-08-11 22:43 UTC, wrgraff commented on source/sass/blocks/page-promo.scss
> +// }
Вообще, для себя комментить код — норма, а вот отправлять закомметированный код в рабочий проект (которым кааааак бы является наш мастер-репозиторий) — плохая практика

2022-08-11 22:43 UTC, wrgraff commented on source/sass/blocks/page-footer.scss
> +    justify-content: space-between;
Не получится )

2022-08-11 22:50 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    width: 45%;
Нет, а зачем ей тянуться? Там все помещается — и хорошо.

Я делал видео по одному из старых проектов, там нет адаптива, но подход можно скопировать:
https://youtu.be/Ccmu3wrjY8o

2022-08-11 22:58 UTC, wrgraff commented
> я немного по разному сделала отступы на разных страницах (в верхних частях - заголовок и описание), т.к. я думаю, что все эти пути корректные и чтобы может быть ты посоветовал, если какой-то из путей более верный)) смотрела на элементы с рамками для наглядности.

Вариант с формой мне видится более удачным )

2022-08-11 22:58 UTC, wrgraff approved these changes

2022-08-11 22:58 UTC, merged