Module5 task1
htmlacademy-adaptive/2071173-cat-energy-26 pull request #5
Opened 2022-08-15 15:21 UTC by kokosmosss

Сделала сетку главной. Пока без состояний для ссылок/кнопок и слайдер не трогала.
Вопросы:
1. Шапка: как правильно менять картинку лого? 
2. Медиа запрос на max-width 767px ("до планшета") - верстка ломается. как это обойти? И еще я хотела сделать переменную для такой ширины, но не придумала как назвать ее... Как лучше?
3. "5кг и 60 дней", не знаю как сделать внизу у линии разрыв. Придумала только квадрат какой-нибудь подложить, но мне кажется вариант не очень.

Я сверилась по pixel perfect - вроде все более-менее. Я помню, что ты писал про размеры отступов из макета и округление, но придется же подгонять под макет в итоге, чего я уже начала немного делать, поэтому некоторые отступы не как в макете вообще.

2022-08-17 10:01 UTC, wrgraff requested changes

2022-08-17 10:01 UTC, wrgraff commented on source/index.html
> +  <header class="page__header page-header page-header--closed center-container">
Все-таки у разработчиков есть устоявшиеся имена для классов, выполняющих определенные функции. Для центровщика это `container`.
Не то чтобы это прям сильно важно было для нашего учебного проекта, тем более если так понятнее зачем он. Но имей ввиду )

2022-08-17 10:01 UTC, wrgraff commented on source/index.html
> +        <h1 class="page-promo__title page-main__title">Функциональное<br>питание для котов</h1>
Я бы предложил оставить расстановку брейков на сааамый конец. Хочется сперва посмотреть как сайт будет работать без них. Ведь что, если наш сайт затем наполнит контент-менеджер, который о них не задумается? Как контент встанет на страницу без форматирования руками?
Чтобы это увидеть можно сперва постараться все сделать без брейков. А потом уже для ПП их добавить по необходимости

2022-08-17 10:01 UTC, wrgraff commented on source/index.html
> -        <img class="page-promo__image" src="img/promo.png" width="280" height="270" alt="Корм Cat Energy Pro с курицей.">
Ой, а зачем ты целиком удалила изображение? Мы же уже по идее решили, что оно контентное.
Получается, у нас уже есть какая-то тактика с самого начала. И мы должны ее придерживаться.

2022-08-17 10:01 UTC, wrgraff commented on source/index.html
> +        <a class="button button--program page-promo__button" href="program.html">Подобрать программу</a>
А что это за страница такая `program.html`? Это или несуществующая, или наверное наша страница формы — надо поставить тогда не нее ссылку (ну или `#`)

2022-08-17 10:01 UTC, wrgraff commented on source/index.html
>            </p>
Надо или закрыть на строке
```suggestion
          <p class="feachures__description">Уже через месяц наслаждайтесь изменениями к лучшему вашего питомца!</p>
```

Ну или разнести уж
```suggestion
          <p class="feachures__description">
            Уже через месяц наслаждайтесь изменениями к лучшему вашего питомца!
          </p>
```

2022-08-17 10:01 UTC, wrgraff commented on source/index.html
> +          </div>
Вышло все по делу

2022-08-17 10:01 UTC, wrgraff commented on source/index.html
> +      title="Офис компании по адресу ул. Большая Конюшенная, д. 19/8, Санкт-Петербург"></iframe>
Я бы все эти параметры повыкидывал, может быть кроме ширины и высоты

2022-08-17 10:01 UTC, wrgraff commented on source/index.html
> +              <svg width="27" height="17" viewBox="0 0 27 17" fill="none" xmlns="http://www.w3.org/2000/svg"
Смотри, когда встраиваешь svg в код, параметр `xmlns` можно удалить.
Он помогает браузеру понять, что это будет xml-подобный код. И для внешнего файла это нужно, он без этого картинку не отобразит. А здесь мы и так уже внутри html, так что никаких проблем.

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/contacts.scss
>    display: grid;
Нужно учиться не только решать задачу построения контента по макету, но и учиться видеть принцип построения элементов. Они у тебя сейчас идут вплотную. На ширине как в макете все выглядит как надо, но если ширина меняется, то текст может "слипнуться":
![изображение](https://user-images.githubusercontent.com/37917037/184964325-3b9efd37-4b7b-4564-a6ed-f17dc4a955d4.png)

А значит, нужен некий гэп между текстами.

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    left: 110px;
Получилось почти как надо, на нужно сделать так, чтобы и на большой ширине плашка стояла в линию с контентом, а сейчас она просто остается у левого края:
![изображение](https://user-images.githubusercontent.com/37917037/184964661-dfa55ac4-4530-4842-bee9-d4f0c604bca0.png)

<details>

<summary>Внимание, спойлеры (подсказка как это сделать)</summary>

Ты можешь решить эту проблему привязав элемент не к левому краю, а к центру страницы. То есть, будет `left: 50%`. А затем сдвинуть его влево на ширину, равную половине ширины контента. Через `calc()` или отрицательный отступ слева.

</details>

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/example.scss
> +  br {
А вообще, у тебя же все равно уже есть `span`. Можно его сделать блочным в определенный момент и тогда текст поделится на 2 строки. И брейк уже и не нужен будет

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/feachures.scss
> +  content: counter(feachures__counter);
Ого, счетчик сразу! Здорово )

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/feachures.scss
> +}
Красота

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/feachures.scss
> +
Как-то я упустил раньше: пишется `features`

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/feachures.scss
> +  display: none;
Ну, ты могла бы `content` написать в медиа-запросе для планшета. На мобильном размере псевдоэлемент без этого свойства и не показался бы )

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/feachures.scss
> +    display: block;
Писать `display` нормально, особенно для декларативности, но все же скажу: все элементы при абсолютном позиционировании становятся блочными

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/nav-list.scss
> +  @media (min-width: 767px) {
А почему 767?

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/nav-list.scss
> +  @media (max-width: 767px) {
Обычно для такого брейкпоинта создают переменную в стиле `$mobile-only` или `$mobile-down`.
Создать ее при этом можно через подсчет от другой переменной: `$tablet - 1px`.

Вообще, про брейкпоинты можно хорошенько поговорить еще и обсудить в чем проблема. Потому что мы часто путаемся и называем брейкпоинты так, словно это диапазоны...

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/pack.scss
> +  background-image: url("../img/icons/arrow.svg");
Я бы рекомендовал ставить длинный вариант стрелки, как при наведении. И смещать его, скрывая часть стрелки, чтобы при наведении тебе нужно было бы ее только подвинуть, а не как-то растягивать или менять картинку

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/packs.scss
> +  background-image: url("../img/cat-back-sit.svg");
Часто такие картинки экспортируют без фона. Поскольку фон можно нарисовать CSS-ом.

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/feachures.scss
> +  background-image: url("../img/icons/leaf.svg");
Обычно такие картинки экспортируют без фона, чтобы они были меньше и в случае чего цвет фона можно было бы изменить (мало ли они интерактивные будут или чуть сменится дизайн блока).

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +  grid-template-columns: 1fr 1fr;
Ну вот, получилось. Правда, это решение вышло распределенным по 2 блокам... Но может тут иначе прям идеально по БЭМу и не сделать.
Как я говорил, все не так легко здесь =)

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +  grid-template-columns: auto 30%;
Будет точнее, если сделать `1fr 1fr 1fr` (фр-фр-фр 😄)
И затем `.page-header__logo` поместить в 2 первые колонки

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +// я вот тут намудриса с этими рисунками, а дальше вот с этим переключением классов не соображу, можно ли их менять, чтобы кнопка менялась. или лучше сразу на иконки поменять?
Здесь довольно простые изображения.
Обычно я студентам рекомендую не заморачиваться на таком и ставить картинки. Но раз уже сделала, то зачем отказываться? Твой способ, кстати, позволит их при переключении красиво анимировать. Ну, если чуть-чуть доработать. Так что я бы оставил уже так

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/page-promo.scss
> +    width: 720px;
Картинка то не тянется, получается =(

![изображение](https://user-images.githubusercontent.com/37917037/185091412-5a8a81e4-715f-4d46-842e-0ae1d5ac9a28.png)

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/page-promo.scss
> +// у меня для эмой кнопки еще модификатор есть. я туда ничего не вписала. по моему туда только падинг можно вынести. или вообще тут он и не нужен?
Я бы вынес паддинг, потому что для кнопки это часть самой кнопки. Будет логично, если параметрами паддинга, высоты строки и размера шрифта будет управлять модификатор самой кнопки

2022-08-17 10:01 UTC, wrgraff commented on source/sass/blocks/param-list.scss
> +  text-transform: lowercase;
Обрати еще внимание на шрифт этих элементов

2022-08-17 10:09 UTC, wrgraff commented
Вышло довольно хорошо. Отвечу на вопросы )

> Шапка: как правильно менять картинку лого?

Вас этому научат чуть позже, в разделе про адаптивную графику. А до той поры лого немножко убогеньким останется, придется подождать

> Медиа запрос на max-width 767px ("до планшета") - верстка ломается. как это обойти? И еще я хотела сделать переменную для такой ширины, но не придумала как назвать ее... Как лучше?

Не заметил, что там ломается что-то.
Про переменную написал, но это хорошая тема, чтобы более обстоятельно обсудить на консультации.

> "5кг и 60 дней", не знаю как сделать внизу у линии разрыв. Придумала только квадрат какой-нибудь подложить, но мне кажется вариант не очень.

Ну на самом деле ничего особо умного и нет, так что подложить квадрат — это то, что мы и делаем =)
Но нужно постараться, чтобы "квадрат" все-таки зависел от объема текста.

> Я сверилась по pixel perfect - вроде все более-менее. Я помню, что ты писал про размеры отступов из макета и округление, но придется же подгонять под макет в итоге, чего я уже начала немного делать, поэтому некоторые отступы не как в макете вообще.

Да они и не будут как в макете, это нормально. Как минимум, рендер шрифтов в браузерах отличается и может быть другая высота блоков текста. А еще в этих макетах часто неадекватная высота строки стоит 1 к 1, что вредно для переполнения и в верстку переносить не стоит. Но когда мы это фиксим, наша строка станет по высоте чуть больше.

> А, ну и еще вот с мобильным меню не очень все еще понятно, что за реализация без js. зачем вообще специальный класс добавляют...

Окей, я понял, что тут у тебя не все сложилось как работает и в чем суть. В принципе, реализация то нормальная и сейчас, поэтому ты пока ее не трогай, а после консультации цже внесешь пару правок. На консультации я расскажу поподробнее тогда что это и как работает. И пример покажу наглядный.

2022-08-17 13:45 UTC, kokosmosss commented on source/index.html
> -        <img class="page-promo__image" src="img/promo.png" width="280" height="270" alt="Корм Cat Energy Pro с курицей.">
Так я я подумала, что его так будет проще перестроить)) да и оно же не контентное по своей сути. Банку можно убрать и смысл не потеряется - подумала я и решила переделать.

2022-08-17 13:50 UTC, kokosmosss commented on source/index.html
> +      title="Офис компании по адресу ул. Большая Конюшенная, д. 19/8, Санкт-Петербург"></iframe>
А title как же?

2022-08-17 14:06 UTC, kokosmosss commented on source/sass/blocks/nav-list.scss
> +  @media (min-width: 767px) {
Сама не поняла уже, почему там это вылезло...

2022-08-22 08:36 UTC, kokosmosss commented
Что тут не сделано:
- я не стала переделывать иконки и делать фон css. они вроде не много весят и не интерактивные, я сознательно выбрала этот способ в данном случае, но помню про фон))
- зеленые полоски у меня не вышли. в каталоге увидишь, что происходит на десктопе, в форме я пока просто закомментировала. Я уже как не изворачивалась и обертки добавляла, пробовала как на лайве, все криво. я буду думать над ними дальше, просто я так вообще никогда эту домашку не закрою, если буду сидеть с ними.
- состояния не все сделаны + нет иконок в форме, я это доделаю позже. некоторые состояния я добавила, чтобы посмотреть что все работает.
- js для меню я не делала, я хочу им заняться вместе со слайдером.

Вопросы:
- что такое состояние down в сталгайде? 
- у меня не вышло сделать увеличение иконки стрелки на главной при наведении. я кстати ее и через маску пробовала делать, тоже не вышло двигать. в чем там проблема?
- textarea не встает как на макете. ей надо высоту задавать, а не rows? у нее получается размеры от версий разные, но вроде  rows нельзя править через css?

2022-08-22 21:20 UTC, wrgraff commented on source/index.html
> +      title="Офис компании по адресу ул. Большая Конюшенная, д. 19/8, Санкт-Петербург"></iframe>
А ты знаешь что он делает? =)
На картинках он при наведении в течение нескольких секунд показывает около курсора эту надпись. При чем доступности не добавляет, никак не читается нигде. А потому и не используется уже почти нигде

2022-08-22 23:23 UTC, wrgraff requested changes
> я не стала переделывать иконки и делать фон css. они вроде не много весят и не интерактивные, я сознательно выбрала этот способ в данном случае, но помню про фон))

Все-таки, так обычно не делается. Доступно более гибкое решение, которое позволит соотношение размеров между иконкой и плашкой регулировать из кода. Обычно разработчики любят такую гибкость.

> что такое состояние down в сталгайде?

Это нажатие, соответствует состоянию `:active` в CSS

> у меня не вышло сделать увеличение иконки стрелки на главной при наведении. я кстати ее и через маску пробовала делать, тоже не вышло двигать. в чем там проблема?

Ну в этом плане фон от маски то и не отличается. Я там написал в самом ревью: надо работать с позицией фона, не с размером.

> textarea не встает как на макете. ей надо высоту задавать, а не rows? у нее получается размеры от версий разные, но вроде rows нельзя править через css?

Нужно постараться сделать через rows, высоту строки и отступы. Если не получится, можно махнуть рукой и поставить высоту.

--- 

Я прошелся по коду и вопросам, не хватило времени и сил на сами сетки и все эти полоски. Сделаю еще второй заход с рекомендациями чисто по ним. А пока думаю с этими комментариями тоже найдешь чем заняться =)

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    transform: translateX(calc(-1220px / 2));
Ох, что-то ты тут напутала.

`calc()` — это возможность не препроцессора, а CSS. Ее основная сила в том, что так как ее считает браузер, он может работать с единицами измерения разных типов, например вычитать из процентов пиксели (из относительного значения абсолютное).

`1220 / 2` Ну, как бы: `= 610`. То есть, ты могла бы использовать результат. Зачем мы его вычисляем, если оба значения известны заранее?
Если же ты хотела использовать переменную препроцессора, чтобы вычислить значение на выходе, то стоит писать так: `math.div($large, -2)`. При этом нужно будет использовать `@use` дли импорта модуля `math`. Да и размер брейкпоинта и размер экрана у тебя не совпадают, поэтому понадобилось бы еще вычислять что-то.

И еще: `transform` следует использовать в последнюю очередь, так как он довольно прожорлив в плане производительности. Соответственно, более простым и легким для восприятия был бы такой код сразу же в позиционировании:

```css
left: calc(50% - 610px);
```

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/nav-list.scss
> +}
А зачем при нажатии на ссылку добавлять рамку? У нас ее в интерактивных ссылках как раз нет, она есть только на той ссылке, которая с адресом.

У тебя вот так выходит:
![изображение](https://user-images.githubusercontent.com/37917037/186025926-7c2b45d1-d9be-4a1f-94fc-b6a9be142b2a.png)

А в стайлгайде вот:
![изображение](https://user-images.githubusercontent.com/37917037/186025984-6c6a07ea-5fe6-47d2-9980-9a8946c7f020.png)

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/pack.scss
> +// почему то не работает изменение стрелки? картинку заменила на побольше
Потому что svg не позволяет искажать картинку и все равно внутри фона масштабирует ее за счет `viewBox`. Нужно не менять размер, а смещать фон так, чтобы кусок "черенка стрелки" срезался

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +}
Это мы получается когда меню закрыто скрываем целиком кнопку?..
Но нам кнопка то нужна.

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +  visibility: hidden;
Почему вдруг через `visibility`?

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/button.scss
> +  box-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);
А зачем ей тень? У нас при нажатии нет тени

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/button.scss
> +  color: rgba(94, 170, 47, 0.3);
Цвет текста должен оставаться белым, а значения `94, 170, 47` — явно не белый. Судя по всему, это наш зеленый. Но ведь ты меняешь цвет текста, а не фона — он не должен быть зеленым.

Кроме того, гораздо приятнее благодаря препроцессору писать так:
```suggestion
  color: rgba($white, 0.3);
```
Только надо помнить, что это опция препроцессора, css так не умеет и это на самом деле функция `rgba()` разворачивается в настоящий цвет при компиляции.

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/button.scss
> +  width: 280px;
Ну почему ширина переехала с модификатор кнопки, она должна была оставаться в элементе, мы же много раз повторяли, что размерами внешний блок управляет =(

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/catalog-adds.scss
> +  // тут все плохо. у меня не получается сделать.
Все равно отправляй лучше криво работающее, чем коммент. Мне же все равно раскомментить надо, чтобы посмотреть )

2022-08-22 23:23 UTC, wrgraff commented on source/catalog.html
> +      <section class="catalog-adds catalog-adds--decor">
Не понял зачем тут модификатор, этот блок у нас один такой

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/button.scss
> +.button--order {
В нормальной ситуации у нас были бы модификаторы совсем другого рода.
`--secondary`, `--primary` для обозначения цветов
`--large`, `--small` для обозначения размеров отступов и текста
Может, другие какие-то опции. У кнопок много видов и форм бывает, зависит от дизайна.

К моему сожалению, Академия считает, что давать плохой макет, где придется на каждое применение кнопки вешать отдельный модификатор — это хорошая идея, чтобы подготовить к плохим макетам.
Как по мне, так это большое упущение, которое не позволяет увидеть вам "как должно быть".

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/card-adds.scss
> +    display: grid;
Всегда напрягаюсь, когда меняется при другом брейкпоинте меняется флекс на грид или наоборот.
У нас по сути кнопка была внизу, а затем встала в ряд. Зачем же такие изменения в подходе?

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/card.scss
> +  flex: 0 0 50%;
А ты прям хорошо понимаешь эту краткую запись? Я вот так сходу даже и не помню что это значит

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/card.scss
> +  text-overflow: ellipsis;
А при чем тут ellipsis?

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/field.scss
> +  grid-template-columns: auto 1fr; // вот тут я долго думала как сделать чтобы "возраст (лет)" не переносилось. и инпуту задавала максимальную ширину 100%, и разные размеры колонок пробовала, ничего
Например, так должно сработать:
```css
  grid-template-columns: max-content 1fr;
```

Но второй частью должно стать обнуление минимальной ширины у `.field__input`, так как по умолчанию инпут получает ее от браузера (это немного неожиданно, так как обычно браузеры не трогают это свойство, но иногда они способны удивить)

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/field.scss
> +  resize: none;
Не надо, пускай остается

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/field.scss
> +  }
Текст в самом инпуте и его плейсхолдер должны совпадать по размерам, высоте строки, стилю и прочему. Иначе заполненный инпут выглядит странно рядом с пустыми:
![изображение](https://user-images.githubusercontent.com/37917037/186033249-da622969-ebb0-4417-b22d-1e9562a4745e.png)

Поэтому стили текста задаются самому инпуту, а для плейсхоледра — цвета и прозрачность

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/field.scss
> +  overflow: hidden;
Это же инпут, зачем ему такое вообще?
Там и так свои законы

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/form-checkbox.scss
> +    grid-template-columns: 1fr 1fr 1fr 1fr;
Кстати, можно еще так писать
```suggestion
    grid-template-columns: repeat(4, 1fr);
```

2022-08-22 23:23 UTC, wrgraff commented on source/sass/blocks/pack.scss
> +.pack__button:hover .pack__button::after {
Получается, структура дерева для такого селектора будет такой:
```html
<element class="pack__button"> (hover)
  <element class="pack__button">
    :after
  </element>
</element>

Что-то тут не то, откуда вложенность кнопки в кнопку?

2022-08-22 23:23 UTC, wrgraff commented on source/sass/global.scss
> +// я пока не сделала медиазапрос, у меня в каталоге почему то еще до планшета он начинал работать... не знаешь почему?)
Из-за реализации "прилипающего футера".
У тебя стоит колоночный флекс на `.page__body`. Это делает `.page-main` элементом флекса, направленного сверху вниз. По умолчанию он растягивается, но автоотступы во флексе отталкиваются, если есть такая возможность. Возможность есть, вот оно и отталкивается, даже при этом поджимая контент.

Не очень удачно, что `page-main` и `center-container` у тебя миксуются вместе, при чем делают это только на странице каталога. Я бы не рекомендовал вообще делать на `page-main` разный набор блоков. Может быть, модификатор, если нужно.

Будет лучше обернуть какой-нибудь внутренний элемент на странице каталога, а не весь main

2022-08-24 16:46 UTC, kokosmosss commented on source/sass/blocks/nav-list.scss
> +}
ну да, это я нафантазировала😃
вот если брать состояния из фигмы, то там все просто: ховер - opaciy 0.3, active - 0.6, но 0.6 не видно. я сделала через pick color и поменяла цвет. так можно? этот проект уже можно называть 50 оттенков серого ))) в переменных, да и не только 😂

2022-08-24 17:29 UTC, kokosmosss commented on source/sass/blocks/page-header.scss
> +}
это получается у нас кнопки-крестика нет и вместо нее кнопка-бургер.
я немного поправила и написала комментарий как оно работает. вроде работает ))

2022-08-24 17:29 UTC, kokosmosss commented on source/sass/blocks/page-header.scss
> +  visibility: hidden;
Почему-то меня смутило, что меню будет удаляться из потока... хотя вроде это и ок?

2022-08-24 18:00 UTC, kokosmosss commented on source/sass/blocks/card-adds.scss
> +    display: grid;
наверное как то гридом можно было... но они тут не по колонкам вообще стоят, и показалось флексом лучше будет, но все равно пришлось изворачиваться.

2022-08-24 18:04 UTC, kokosmosss commented on source/sass/blocks/card.scss
> +  flex: 0 0 50%;
стараюсь научиться понимать и ее)

2022-08-27 18:25 UTC, kokosmosss commented
1. я переделала иконки все. в блоке packs мне кажется вышло сложнее конструкция, но мб был путь проще переделать, которого я не знала.
2. полоски. везде все получилось, кроме одного места. "контактные данные владельца кота" на мобильнике, до тех пор пока текст не перенесется, полоска не прижимается как надо. уже не знаю что и делать... с 407px ширины экрана все нормально встает.
3. что-то случилось с формами, начиная с блока "контактные данные владельца кота" и далее все после него (даже чекбоксы) не выбираются мышкой, на них нельзя нажать. при этом табом можно выбрать. что это значит?) кажется, это произошло, пока я полоски делала.

2022-08-29 19:09 UTC, wrgraff commented on source/index.html
> +        <div class="page-promo__container">
3 обертки! 😱

2022-08-29 19:09 UTC, wrgraff commented on source/sass/blocks/nav-list.scss
> +}
Лучше так не делать. Вдруг фон изменится. Да и зачем лишний цвет вводить в интерфейс, который на самом деле результат перекрытия. Лучше чтобы он как в исходнике нашем создавался аналогичным методом. Всегда лучше, когда мы воспроизводим сам подход

2022-08-29 19:28 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +}
Но у тебя же в разметке одна кнопка. И ты добавлешь на нее модификаторы `--open` и `--close`.
Получается, что у тебя не кнопка исчезать должна, а меняться картинка с бургера на крестик и наоборот

2022-08-29 19:31 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +  visibility: hidden;
Это ок, нам же и нужно удалить его из потока. Если останется в потоке, это же пустое место будет вместо меню, а контент не подтянется

2022-08-29 19:37 UTC, wrgraff commented on source/sass/blocks/card-adds.scss
> +    display: grid;
98% случаев когда идет переключение из флекса в грид или наоборот — это от недостатка понимания работы флекса или грида. Обычно проще перестроить что-то в рамках существующей сетки, чем менять ее полностью.
Тут тоже вполне можно было бы )

2022-08-29 19:37 UTC, wrgraff commented on source/sass/blocks/card.scss
> +  flex: 0 0 50%;
Зачем?
Можно же писать гораздо понятнее и себе и другим

2022-08-29 21:12 UTC, wrgraff requested changes

2022-08-29 21:12 UTC, wrgraff commented on source/sass/blocks/form-checkbox.scss
> +    grid-column: span 4;
Тебе приходится переписывать количество колонок, потому что оно меняется при изменении ширины экрана, а тебе нужно, чтобы заголовок занимал все колонки.
Вопрос: а можно ли сделать иначе? Например, прям сказать ему "займи все колонки от первой до последней". Тогда не придется переписывать, при любом количестве заголовок растянется. И...

Конечно, можно!
Для этого нужно указать не через `span` заполнение, а начало и конец по линиям (от первой до последней):
```suggestion
    grid-column: 1 / -1;
```

2022-08-29 21:12 UTC, wrgraff commented on source/sass/blocks/logo.scss
> +}
Можно еще так
```suggestion

.logo:link:hover {
  opacity: 0.8;
}

.logo:link:active {
  opacity: 0.6;
}
```

Формально это получается как бы правильнее, хотя работать будет и то и то

2022-08-29 21:12 UTC, wrgraff commented on source/sass/blocks/pack.scss
> +  // background-size: 32px 12px;
=/

2022-08-29 21:12 UTC, wrgraff commented on source/sass/blocks/nav-list.scss
> +    color: $white;
Этот стиль перебивает стили нажатия и при `:active` на главной на десктопе не меняется цвет =(

2022-08-31 09:12 UTC, kokosmosss commented on source/sass/blocks/page-header.scss
> +}
у меня нет модификатора --open. у меня есть кнопка toggle = бургер и ее модификатор --close
![image](https://user-images.githubusercontent.com/103606827/187643170-36dda33b-797a-46dd-a738-9f54d9b3c361.png)

2022-08-31 10:55 UTC, kokosmosss commented on source/sass/blocks/card-adds.scss
> +    display: grid;
мне вообще уже эта сетка не нравится как сделана...

2022-08-31 13:25 UTC, wrgraff approved these changes

2022-08-31 13:25 UTC, wrgraff commented on source/form.html
> +              Контактные данные <br>
Надо было добавить, что такое лучше через класс на `<br>` делать, а то я для простоты по тегу правил

2022-08-31 13:25 UTC, merged