Module6 task1
htmlacademy-adaptive/2071173-cat-energy-26 pull request #6
Opened 2022-08-31 21:31 UTC by kokosmosss

*Тут по сути и 6 задание, и 7 вместе. Все уже почти по макету везде, за исключением шапки и мелких недочетов. Над шапкой я еще подумаю.
*Я переделала сетку в дополнительных товарах, теперь она выглядит получше. Но там появился отрицательный маржин, иначе не придумала как засунуть в гэп. Посмотри, пожалуйста, ок ли так.
*Теперь вопросы, которые у меня остались:
1. Форма, десктоп, блок с радио кнопками. Коробочка снизу имеет какой-то непонятный отступ (если смотреть, то он прям над нижним паддингом), не могу понять откуда он берется. Он не выделяется в браузере и на планшете его нет.
2. Иконки в форме. Не получилось сделать состояния - смену цветов. Телефон меняет цвет, а письмо нет. И туда же вопрос по поводу оформления ошибки - это делается через отдельный класс или через состояние invalid?
3. В каталоге последняя карточка - show more кривая в той части, что ей вручную приходится задавать маржин сверху, чтобы она выравнивалась по серому цвету карточек. Ведь они могут поменять высоту, а маржин в абсолютной величине.

2022-09-01 18:32 UTC, wrgraff requested changes
Хорошая работа

2022-09-01 18:32 UTC, wrgraff commented on source/catalog.html
> +          <source media="(min-width: 1330px)" srcset="img/logo-desktop.svg">
Не очень понятно, почему стоит 1330, если у нас переход на 1300.
Конечно, ничего у нас от этого не сломается и даже критерии ты нормально пройдешь, потому что проверять будут разрешение по макету. But why? =)

2022-09-01 18:32 UTC, wrgraff commented on source/catalog.html
> +                srcset="img/catalog/chicken-pro-500-tablet.webp 1x, img/catalog/chicken-pro-500-tablet@2x.webp 2x">
На самом деле, разница между картинкой среднего размера и картинкой десктопа такая, что больше напоминает погрешность.
И будь этот макет оформлен как следует, картинка бы наверное никак не масштабировалась.

Я бы предпочел чуть меньше точность и при этом чуть меньше же и телодвижений и кода.
Но мы, разработчики, люди чрезвычайно ленивые, так что смотри сама )

2022-09-01 18:32 UTC, wrgraff commented on source/catalog.html
> +              </picture>
А почему в первой картинке webp есть, а в остальных нет?
На автоматизацию оставляем (я только за, я же упоминал уже про ленивость...)?

2022-09-01 18:32 UTC, wrgraff commented on source/catalog.html
> +  <script src="/js/menu.js"></script>
Путь неверный, он абсолютный. Скрипт надо подключать так же, как и все остальное: картинки, стили и прочее.
Напомню, что при публикации через ГитХаб такие ссылки не сработают правильно, потому что корневая папка там будет не `source`, как у тебя

2022-09-01 18:32 UTC, wrgraff commented on source/form.html
> +            </svg>
Вот что еще заметил (это конечно проблема сеток, но мы эту проблему там пропустили). Клик по иконке, которая визуально внутри поля находится, ни к чему не приводит. А тут довольно очевидно, что иконка вообще должна казаться частью фона поля.

На мой взгляд, один из простейших вариантов — расположить ее под полем, а поле сделать прозрачным.

2022-09-01 18:32 UTC, wrgraff commented on source/sass/blocks/field.scss
> +  display: block;
Судя по настройке далее — это элемент грида. Нет смысла ему задавать `block`, так как он все равно будет вести себя как "грид-элемент", так сказать

2022-09-01 18:32 UTC, wrgraff commented on source/sass/blocks/field.scss
> +.field__icon {
Помимо позиционирования иконки нужно иметь ввиду, что при заполнении поля текст не должен на иконку наползти. А у нас наползет:
![изображение](https://user-images.githubusercontent.com/37917037/187983342-9be5af8e-f822-4a76-a06b-2c1d11ee529e.png)

Решение простое. Место, занимаемое иконкой зарезервировать с помощью паддинга самого поля.

2022-09-01 18:32 UTC, wrgraff commented on source/sass/blocks/field.scss
> +.field__input:not(:placeholder-shown) + .field__icon {
Вот этот вот селект `:not(:placeholder-shown)`, которому вас зачем-то научили на первом уровне (читай забили голову ненужной ерундой) вообще не особо где-то используется.

Начнем с вопроса что вообще этот селектор позволяет нам вычислить?
Есть ли текст в поле или нет.

Посмотрим стайлгайд:
![изображение](https://user-images.githubusercontent.com/37917037/187984256-fba9bc4c-c6b3-4379-8c5f-4f89e5fb17d3.png)

Здесь нет таких сложных сочетаний, все просто: статика, наведение, фокус. То есть, наше поле должно выглядеть как состояние фокуса и пустым в том числе.
99% стайлгайдов будут именно такими.

Единственное, для чего может здесь понадобиться такой селектор — это состояние ошибки. Чтобы не показывать ее пока поле пустое (`:invalid` увы так делает), можно назначить на пустое поле скрытие стилей ошибки.
Однако, чаще всего ошибку не нужно показывать, если поле пустое только пока пользователь его не потрогал. Если он повзаимодействовал с обязательным полем и не заполнил его — надо его подсветить. Для этого есть селектор `:user-invalid`, но он пока не работает достаточно хорошо во всех браузерах. Поэтому мы используем обычный класс, который будет подключать js, так как он отлично умеет разбираться с валидацией.
Но в обоих подходах `:placeholder-shown` нам не пригодится.

2022-09-01 18:32 UTC, wrgraff commented on source/js/slider.js
> +// });
А это чего такое )
Тут скорее всего для работы на мобильных реализация, там событие клика не сработает так, чтобы тащить ползунок.
Наверное, надо и эту часть включить? 

Хотя, нам это не принципиально

2022-09-01 18:32 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +    border-bottom: 1px solid $grey-370;
Из-за того, что добавляется рамка, высота хэдера на 1px меняется и при открытии/закрытии меню вся страница чуть дергается.

Надо или придумать так, чтобы там всегда была рамка (например, она превратится в рамку между первым пунктом меню и хэдером), или же сделать ее как-то визуально так, чтобы не изменился размер самого элемента.
Первый вариант на мой взгляд получше

2022-09-01 18:32 UTC, wrgraff commented on source/sass/blocks/field.scss
> +  stroke: $green-300;
Иконка письма не меняется, потому что скорее всего там не `stroke`

2022-09-01 19:32 UTC, wrgraff commented
> Форма, десктоп, блок с радио кнопками. Коробочка снизу имеет какой-то непонятный отступ (если смотреть, то он прям над нижним паддингом), не могу понять откуда он берется. Он не выделяется в браузере и на планшете его нет.

Это скорее пустота, чем отступ. Она создается из-за того, что в гриде `program-form__container` колонки растягиваются по высоте относительно той, что выше. Попробуй например обнулить отступ у последнего поля в левой колонке.
![изображение](https://user-images.githubusercontent.com/37917037/187997184-e4ced408-3a50-4c86-a017-b275846fb058.png)

2022-09-01 19:33 UTC, wrgraff commented on source/sass/blocks/card-adds.scss
> +  grid-template-columns: 1fr 1fr;
Я бы не делал равные расстояния, можно вообще колонке справа выдать фикс размер какой-то, потому что там только и есть, что вес или объем, они много места не займут.

2022-09-01 19:36 UTC, wrgraff commented
> В каталоге последняя карточка - show more кривая в той части, что ей вручную приходится задавать маржин сверху, чтобы она выравнивалась по серому цвету карточек. Ведь они могут поменять высоту, а маржин в абсолютной величине.

А почему ты выбрала градиент для `.catalog__item` снизу вверх, а не наоборот?
Ведь если описание станет больше, то такой градиент будет спускаться все ниже и ниже. И в итоге может даже начаться под картинкой. Дизайном же предусмотрен скорее фиксированный отступ фона от верха.
И поэтому и карточке подзагрузки вполне нормально задать фиксированный отступ сверху.

Кстати, градиент должен бы относиться скорее к `.card`, это ведь часть оформления карточки, если она будет переиспользоваться, то с фоном

2022-09-02 12:58 UTC, kokosmosss commented on source/catalog.html
> +          <source media="(min-width: 1330px)" srcset="img/logo-desktop.svg">
это ошибка

2022-09-02 13:04 UTC, kokosmosss commented on source/catalog.html
> +              </picture>
конечно же! в задании так и было написано, потренируйтесь))

2022-09-02 13:17 UTC, kokosmosss commented on source/catalog.html
> +                srcset="img/catalog/chicken-pro-500-tablet.webp 1x, img/catalog/chicken-pro-500-tablet@2x.webp 2x">
и правда. 
я еще не настоящий разработчик, чтобы лениться, так что все лишнее удалила)

2022-09-02 18:39 UTC, kokosmosss commented on source/js/slider.js
> +// });
когда я ее включаю, слайдер перестает работать вообще.
поэтому я это убрала.

2022-09-03 11:47 UTC, wrgraff commented on source/sass/blocks/field.scss
> +// }
Нужно отучиваться от того, чтобы оставлять в пулл-реквестах закомментированный код. МЫ конечно учимся, но у нас симуляция работы с продуктом. Так вот, временно в какой-то ветке может такой код появляться в процессе работы, но в "чистовик" он попадать не должен.

2022-09-03 11:47 UTC, wrgraff commented on source/sass/blocks/field.scss
> +.field__icon {
Ну вот смотри, логично же: когда ставишь отступы от краев, ты делаешь так, чтобы текст к ним _не прилипал_.
Но почему-то к иконке он прилипает. Да, не налезает, и все хотя бы читаемо, но это ведь тоже не то: элементы не должны слипаться.
<img width="623" alt="изображение" src="https://user-images.githubusercontent.com/37917037/188269032-80a2d622-f0c4-4706-ae75-e7c94414b627.png">

2022-09-03 11:48 UTC, wrgraff commented on source/js/slider.js
> +// });
Тогда удалять надо )

2022-09-03 11:52 UTC, wrgraff approved these changes
Есть недочеты, но не критичные и их можно пофиксить и к следующей домашке

2022-09-03 11:52 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +    z-index: 2;
Самому `.page-header` надо в данном случае задать не 0, а то все оказывается под полем:
<img width="437" alt="изображение" src="https://user-images.githubusercontent.com/37917037/188269144-66074732-39e6-467f-908f-4ea0d02382e9.png">

Тут как раз тот случай, когда надо правильно глобальные блоки распределить

2022-09-03 11:52 UTC, wrgraff commented
🖐🦖

2022-09-03 11:53 UTC, merged