Module7 task1
htmlacademy-adaptive/2071173-cat-energy-26 pull request #7
Opened 2022-09-08 11:17 UTC by kokosmosss

Вопросы:
1. по поводу спрайта. Т.к. у меня много было svg в css, я сделала спрайт из твоей демки. Однако когда он собрался, картинки сильно видоизменились, пришлось переделывать css + вытащила пару картинок из спрайта, чтобы они остались как и были. Это норм ситуация? Как происходит в реальности: когда делаются стили и разметка, сразу собирается спрайт и уже от этого пишется код? Или реально так каждый раз нужно переделывать? И действительно ли нужен этот спрайт?
2. в слайдере, до тех пор пока не нажать на ползунок, толстый кот не виден, потом он возникает. Почему так происходит? мне кажется так ранее не было.

2022-09-09 21:39 UTC, wrgraff requested changes
В целом все хорошо. Но наши коты на главной "до / после" тоже должны быть в `webp` версии

2022-09-09 21:53 UTC, wrgraff commented
> по поводу спрайта. Т.к. у меня много было svg в css, я сделала спрайт из твоей демки. Однако когда он собрался, картинки сильно видоизменились, пришлось переделывать css + вытащила пару картинок из спрайта, чтобы они остались как и были. Это норм ситуация?

Нет, это не норм. Ты немного поспешила, стоило написать мне об этой проблеме, чтобы не пришлось все это переписывать.
Ну... В общем, в чем тут дело. Стаковый спрайт — это несколько svg внутри другой svg. И `viewBox` внешнего svg создает свой собственный "вьюпорт". Таким образом, все картинки масштабируются внутри некоего прямоугольника.
Вообще-то, есть в этом пакете соответствующая настройка `rootviewbox: false`. Но... когда я стал тестировать ее, оказалось, что она не работает 😅 Почему? Добро пожаловать во фронтенд! Если кто-то сделал npm-пакет, это еще не значит, что в нем все работает. И не придется что-нибудь костылить...
Так как на курсе нам костылить не очень хочется, лучше будет использовать другой пакет: `gulp-stacksvg`:

```js
import { stacksvg } from "gulp-stacksvg";

export const sprite = () => {
  return gulp.src('source/img/icons/*.svg')
    .pipe(svgo())
		.pipe(stacksvg({ output: 'sprite' }))
		.pipe(gulp.dest('build/img'))
}
```

> Как происходит в реальности: когда делаются стили и разметка, сразу собирается спрайт и уже от этого пишется код? Или реально так каждый раз нужно переделывать?

В реальности нужно заставить спрайт собираться так, как нам надо. И добавлять иконки в процессе верстки, то есть до того, как финальный спрайт будет собран.

> И действительно ли нужен этот спрайт?

Ну раз уж мы его используем, то лучше конечно использовать по максимуму.
Если использовать картинки отдельно, то загрузка каждой — отдельное подключение, а если спрайт, то он грузится единожды. Конечно, хорошо бы спрайт использовать по максимуму.

2022-09-09 21:55 UTC, wrgraff commented
> в слайдере, до тех пор пока не нажать на ползунок, толстый кот не виден, потом он возникает. Почему так происходит? мне кажется так ранее не было.

У меня больше вопрос почему оно так раньше работало. Не должно было )
Необходимо для `slider__image-wrapper--before` задать изначальную ширину `50%`, иначе он имеет ширину 0 и схлопывается.

2022-09-09 21:56 UTC, wrgraff requested changes

2022-09-09 21:56 UTC, wrgraff commented on gulpfile.js
> +  return gulp.src("source/img/icons/*.svg")
Нужно использовать один стиль кавычек в рамках одного языка:
```suggestion
  return gulp.src('source/img/icons/*.svg')
```

2022-09-09 21:56 UTC, wrgraff commented on gulpfile.js
> +    .pipe(gulp.dest("build/img"));
```suggestion
    .pipe(gulp.dest('build/img'));
```

2022-09-11 21:53 UTC, kokosmosss commented
я перенесла одну иконку, которую вытаскивала ранее (в present-block в каталоге), в папку для спрайта. В итоге иконка все равно ломается и начинает во весь блок располагаться. У меня там для ее свойства bg-size стоит auto, я так понимаю в этом причина? Но ранее у меня также стояло auto. Я еще пробовала удалить viewBox у этой иконки, с размерами помогло, но она перестала вставать по центру. Как мне понять, как настраивать спрайт, чтобы так не было? Я сходила в репозиторий из пакета и там каких-либо настроек не обнаружила :(

2022-09-12 14:40 UTC, wrgraff approved these changes

2022-09-12 14:40 UTC, wrgraff commented on source/index.html
> +          <div class="slider__image-wrapper-after">
А зачем нужно менять модификатор на элемент?

2022-09-12 14:40 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +      padding-top: 20px;
Непонятно, почему используешь внутренний отступ для того, чтобы добавить расстояние _между_ текстом

2022-09-12 14:45 UTC, wrgraff commented
> я перенесла одну иконку, которую вытаскивала ранее (в present-block в каталоге), в папку для спрайта. В итоге иконка все равно ломается и начинает во весь блок располагаться. У меня там для ее свойства bg-size стоит auto, я так понимаю в этом причина?

Да, нужно установить конкретные размеры в пикселях.

> Но ранее у меня также стояло auto. Я еще пробовала удалить viewBox у этой иконки, с размерами помогло, но она перестала вставать по центру. Как мне понять, как настраивать спрайт, чтобы так не было? Я сходила в репозиторий из пакета и там каких-либо настроек не обнаружила :(

Когда ты ставишь значение auto, то полагаешься на размеры самой картинки. Если в ней размер не указан, то результат может быть неожиданным.
В самой иконке размеры есть, в спрайте — нет.
Настраивать спрайт не нужно, тут мы скорее обнаруживаем хрупкое место в самой верстке: что будет, если поменяют картинку? Что, если ее размер не будет подходить? С размером `auto` мы получаем непредсказуемый результат. Лучше указывать какие-то конкретные значения.

2022-09-12 14:45 UTC, merged