Module8 task1
htmlacademy-adaptive/2071173-cat-energy-26 pull request #8
Opened 2022-09-14 20:19 UTC by kokosmosss

посмотри вот на это: 
![image](https://user-images.githubusercontent.com/103606827/190253829-0e8dc341-9924-40e0-a024-f1b69654247c.png)

вот так периодически вычисляются шрифты в блоке "показать еще" в каталоге и оттого текст не встает по макету. но так происходит не каждый раз... то есть было такое, что он вставал нормально и размеры шрифта было в computed такие же точно, как и заданы в стилях.

2022-09-16 09:04 UTC, wrgraff requested changes
Можно оставить пустой alt, а удалять его нельзя, так ты не проходишь проверку валидатором:
https://github.com/htmlacademy-adaptive/2071173-cat-energy-26/blob/4490b34f9e9b2afd90a6580f6d3704b84122d408/source/index.html#L24

Это что, кириллическая `c` в атрибуте `action`? 😀😀
https://github.com/htmlacademy-adaptive/2071173-cat-energy-26/blob/4490b34f9e9b2afd90a6580f6d3704b84122d408/source/form.html#L55

А тут модификатор элемента стоит на блоке:
https://github.com/htmlacademy-adaptive/2071173-cat-energy-26/blob/4490b34f9e9b2afd90a6580f6d3704b84122d408/source/form.html#L144

Ссылки для самопроверки:
- [Валидатор](https://validator.w3.org/nu/#textarea)
- [Проверка БЭМ](https://yoksel.github.io/html-tree/)

2022-09-16 20:55 UTC, kokosmosss commented
![image](https://user-images.githubusercontent.com/103606827/190729517-2d98d883-63cf-4faf-8b5b-125667cf4310.png)

вот об этом поведении меню я говорила. на кнопке с планшета display none. 
я поправила js и вроде как все заработало. но я не уверена, что тут все стало корректно.

2022-09-17 11:44 UTC, wrgraff commented
> вот об этом поведении меню я говорила. на кнопке с планшета display none.
> я поправила js и вроде как все заработало. но я не уверена, что тут все стало корректно.

Нет, пока некорректно, отправлю тебе короткое видео про это (в этот раз правда короткое)

2022-09-17 11:47 UTC, wrgraff commented
В блоке `.page-promo` желательно добиться менее резкого перехода за счет фонового цвета
![изображение](https://user-images.githubusercontent.com/37917037/190855025-58d06a0a-3ed6-430c-b4d0-1467400af253.png)

2022-09-17 12:02 UTC, wrgraff requested changes
Все, думаю js и каталог — это последние важные правки =)

2022-09-17 12:02 UTC, wrgraff commented on source/sass/blocks/card.scss
Вот тут проблема:
https://github.com/htmlacademy-adaptive/2071173-cat-energy-26/blob/aa0704e02964452f2162d2d0b546b06f6494e487/source/sass/blocks/card.scss#L24-L34

Ты не можешь писать подобный код уже потому, что используешь в селекторе элементы разных БЭМ-блоков. Это нарушает основной принцип БЭМа.

Кроме того, в этом нет смысла. Не подстраивать же под каждую картинку код. Картинки приходят с бэка обычно и мы заранее не знаем их размеры. Такое решение не подходит в принципе.

Это решается иначе: создается место под картинку с фиксированной высотой. И картинка располагается  внутри этого места по центру (ну или со смещением).
Картинки скорее всего будут стоять не супер идеально, зато карточки по расположению заголовков и кнопок будут совпадать. Это важнее. Сейчас не совпадают:
![изображение](https://user-images.githubusercontent.com/37917037/190855542-c2c303ad-07f6-4cf5-af29-2d111c2cc615.png)

2022-09-19 08:29 UTC, wrgraff approved these changes

2022-09-19 08:29 UTC, wrgraff commented on source/sass/blocks/page-promo.scss
> +  background-color: rgb(21 35 13 / 85%);
Какой-то сложный цвет )
Там же вроде пипеткой просто серый взять можно

2022-09-19 08:29 UTC, wrgraff commented on source/sass/blocks/card.scss
> +    width: 244px;
Ты не учла, что ширина сломает центрирование внутри ссылки.
Кстати, непонятно нужна ли она вообще тут )

![изображение](https://user-images.githubusercontent.com/37917037/190977683-c6bbd0c4-01dc-42ba-9936-6060d133f6e9.png)

2022-09-19 08:29 UTC, wrgraff commented on source/sass/blocks/card.scss
>  .card__image {
В целом можно повыше все картинки поднять (внутренним отступом там или типа того):

![изображение](https://user-images.githubusercontent.com/37917037/190978366-ff8ba8d2-5959-4eeb-9abf-5a1437b50888.png)

2022-09-19 08:30 UTC, merged